import Head from "next/head";
import Link from "next/link";

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — Compass</title>
      </Head>
      <div style={{
        maxWidth: 800,
        margin: "0 auto",
        padding: "60px 24px",
        color: "#ccc",
        fontFamily: "Arial, sans-serif",
        lineHeight: 1.7,
        background: "#0a0a0a",
        minHeight: "100vh"
      }}>
        <Link href="/" style={{ color: "#c9a84c", textDecoration: "none" }}>
          ← Back to Compass
        </Link>

        <h1 style={{ color: "#fff", marginTop: 32, marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ color: "#888", marginBottom: 40 }}>
          Last updated: March 23, 2026
        </p>

        <p>By using Compass, you agree to these Terms of Service. Please read them carefully before using the service.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>What Compass is</h2>
        <p>Compass is an AI-powered career guidance tool built and operated by Compass, based in Ireland. It is designed to help you explore potential career directions through a natural conversation. It is intended for informational and self-reflection purposes only.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Not professional advice</h2>
        <p>Compass does <strong>not</strong> provide professional career counselling, psychological advice, or financial advice. The guidance provided is generated by an AI and should not be treated as a substitute for advice from a qualified career counsellor, therapist, or financial adviser. Any decisions you make based on Compass output are your own responsibility.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Acceptable use</h2>
        <p>You agree to use Compass only for lawful purposes. You must not:</p>
        <ul style={{ paddingLeft: 24 }}>
          <li>Attempt to overload, abuse, or disrupt the service</li>
          <li>Use the service to generate harmful, illegal, or misleading content</li>
          <li>Attempt to reverse engineer or extract the underlying AI system</li>
          <li>Resell or republish Compass output for commercial purposes without permission</li>
        </ul>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Availability</h2>
        <p>We aim to keep Compass available at all times but cannot guarantee uninterrupted access. We reserve the right to suspend, limit, or discontinue the service at any time without prior notice.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Usage limits</h2>
        <p>To ensure fair access for all users, Compass applies a usage limit of 20 requests per IP address per 24-hour period. This is sufficient for one complete career guidance session including follow-up questions.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Intellectual property</h2>
        <p>The Compass name, logo, and design are the property of Compass. The AI-generated career guidance output is provided for your personal use only and may not be resold or republished without our written permission.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Limitation of liability</h2>
        <p>Compass is provided "as is" without warranties of any kind, express or implied. We are not liable for any decisions you make based on the guidance provided. Career outcomes depend on many factors entirely outside our control. To the maximum extent permitted by Irish law, Compass shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Governing law</h2>
        <p>These Terms of Service are governed by the laws of Ireland. Any disputes arising from your use of Compass will be subject to the exclusive jurisdiction of the Irish courts.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Changes to these terms</h2>
        <p>We may update these terms from time to time. We will indicate the date of the most recent update at the top of this page. Continued use of Compass after any changes constitutes your acceptance of the updated terms.</p>

        <h2 style={{ color: "#fff", marginTop: 32 }}>Contact</h2>
        <p>Questions about these terms? Contact us at: <strong>killianstuart8@gmail.com</strong></p>

        <div style={{ marginTop: 60, paddingTop: 24, borderTop: "1px solid #222" }}>
          <Link href="/" style={{ color: "#c9a84c", textDecoration: "none" }}>
            ← Back to Compass
          </Link>
        </div>
      </div>
    </>
  );
}
